### PR TITLE
.idea file baseline for Make LPA

### PR DESCRIPTION
**Pull request by williamfalconeruk**
## Purpose
Brings project run configs into source control for Make LPA  Live

## Learning
This will break your current PHPStorm config without appropriate preparation. 

 * Exit PHPStorm
 * Backup current run folder  
   `mv .idea .idea-bak`
 * Checkout master/branch
 * Start PHPStorm
 * Remove backup (optional)  
   `rm -R .idea-bak`

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

### CODE REVIEW

**Comment by cooperaj** [comment]
Looks pretty good. Could be worth adding a 'docker-compose up' config much like the 'use' one

**Comment by williamfalconeruk** [comment]
> Looks pretty good. Could be worth adding a 'docker-compose up' config much like the 'use' one

Good point - let me fix that.

**Comment by williamfalconeruk** [comment]
should be ok @cooperaj  - can you take another look?

**Comment by cooperaj** [comment]
Looks good. I'd look at the name of the run configs and remove redundant suffixes. It's ok to call the admin services tests "Admin" for instance.

**Pull request merged**
