### PR TITLE
GOV.UK Frontend Jinja changes

### PR DESCRIPTION
**Pull request by matthew-shaw**
## Purpose

- Removes content from the GOV.UK Frontend Jinja port demo app
- Upgrade GOV.UK Frontend Jinja to latest v1.5.1 release
- Upgrade GOV.UK Frontend to latest v3.14.0 release

## Approach

Very minor issue, just sure you'd want to populate your own meta tags instead of my made up catch-all ones

## Learning

Very pleased you're using our open source package, great to see government departments sharing code between services 🙌🏻. I'm the main maintainer of [govuk-frontend-jinja](https://github.com/LandRegistry/govuk-frontend-jinja) and [govuk-frontend-wtf](https://github.com/LandRegistry/govuk-frontend-wtf), if you have any questions or issues with them I'm happy to try and help you out. Since you're also using Flask and WTForms, you might want to check out the WTForms widgets to help you generate and validate GOV.UK compliant forms as well. More on that [here](https://github.com/LandRegistry/govuk-frontend-wtf#readme) and demo [here](https://github.com/LandRegistry/govuk-frontend-wtf#readme).

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added mandatory tags to terraformed resources, where possible
* [ ] If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* [ ] The product team have tested these changes

### CODE REVIEW

**Comment by williamfalconeruk** [comment]
thanks @matthew-shaw - @nickdavis2001 or @Raffers will take a look!

**Comment by nickdavis2001** [comment]
Hi thanks, @matthew-shaw , we love your demo :)  It'd be great to collaborate on this, trying to work out the best way to communicate. Is x-gov slack any good for you?

**Comment by matthew-shaw** [comment]
@nickdavis2001 Yeah sure I'm on x-gov Slack: mattshaw_hmlr

**Review by nickdavis2001 — APPROVED** [review]
lgtm. Thanks for the helpful contribution :) 🏆

**Review by williamfalconeruk — DISMISSED** [review]

**Comment by williamfalconeruk** [comment]
@matthew-shaw - due to security settings on Circle CI, we were not able to merge directly this branch, apologies for this. @nickdavis2001 is looking at incorporating your code, however through a different route.

**Comment by williamfalconeruk** [comment]
@matthew-shaw @nickdavis2001 - we're closing this PR as we've incorporated your changes, - thanks for the heads up 👍🏻

**Pull request closed without merging**
