### PR TITLE
LPAL-682 Refactor DNS to allow for switching in DR Scenario

### PR DESCRIPTION
**Pull request by williamfalconeruk**
## Purpose
In order to allow dns switching between regions, restructure the environment Level terraform to make DNS a module for outward facing values. This allows the opportunity to rely on the flag for DR enablement.  we also needed to refactor the Config file used by CI to be at root level, so it can also rely on the DR flag in selecting the modules output.

requires a set of state moves for DNS, which means merging mustn't take place until these are applied as per below:

```
tf state mv module.eu-west-1.aws_route53_record.public_facing_lastingpowerofattorney module.environment_dns.aws_route53_record.public_facing_lastingpowerofattorney
tf state mv module.eu-west-1.aws_route53_record.front module.environment_dns.aws_route53_record.front
tf state mv module.eu-west-1.aws_route53_record.admin module.environment_dns.aws_route53_record.admin
```

Fixes LPAL-682 partially, next step is to enable DR in dev.

## Approach
- set up dev environment with RDS as per production
- refactor dns into own module, meaning it can be switched over theoretically with the flag.
- move pipeline tasks config to allow for new dns and modules layout
- reroute outputs as needed, and add conditionals based on DR enabled flag.
- TODO: reset dev setup for RDS

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the LPA service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [x] I have added mandatory tags to terraformed resources, where possible
* [ ] If I added a package.json or composer.json, I also made sure this is included in the script in `.github/workflows/dependabot-update.yml`
* [ ] The product team have tested these changes

### CODE REVIEW

**Review by nickdavis2001 — APPROVED** [review]
lgtm

**Comment by williamfalconeruk** [comment]
before state move done summary
Screenshot 2022-05-19 at 09 26 01

**Comment by williamfalconeruk** [comment]
state moves:
Screenshot 2022-05-19 at 09 28 48

**Comment by williamfalconeruk** [comment]
plan post state moves summary
Screenshot 2022-05-19 at 09 29 48

**Pull request merged**
